[project]
name = "deepfilternet-rs"
version = "0.1.1"
description = "PyO3 bindings for the official DeepFilterNet Rust realtime runtime"
readme = "README.md"
authors = [{ name = "di-osc" }]
requires-python = ">=3.10, <3.13"
license = { text = "MIT" }
keywords = ["audio", "denoise", "deepfilternet", "pyo3", "rust"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Rust",
    "Topic :: Multimedia :: Sound/Audio",
]
dependencies = ["numpy>=1.24", "jsonargparse>=4.35,<5"]

[project.scripts]
deepfilternet = "deepfilternet_rs.cli:main"

[project.urls]
Homepage = "https://github.com/di-osc/DeepFilterNet-rs"
Repository = "https://github.com/di-osc/DeepFilterNet-rs"
Issues = "https://github.com/di-osc/DeepFilterNet-rs/issues"

[build-system]
requires = ["maturin>=1.8,<2.0"]
build-backend = "maturin"

[tool.uv]
cache-keys = [
    {file = "pyproject.toml"},
    {file = "rust/Cargo.toml"}, 
    {file = "**/*.rs"}
]

[tool.maturin]
python-source = "python"
module-name = "deepfilternet_rs._native"
features = ["pyo3/extension-module"]
include = [
    "python/deepfilternet_rs/py.typed",
    "python/deepfilternet_rs/models/*.tar.gz",
]
